##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.ksql_cli:5.4.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "ksql"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="ksql_cli" \
    CONTECO_NAME="base" \
    CONTECO_TAG="5.4.0" \
    CONTECO_BASE="external.ksql_cli:5.4.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="ksql_cli" \
      io.vcweb.name="base" \
      io.vcweb.tag="5.4.0" \
      io.vcweb.base="external.ksql_cli:5.4.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="ksql_cli.base - Conteco " \
      io.vcweb.description="Confluent KSQL CLI base image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.ksql_cli.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
