#!/usr/bin/env bash

export CONTECO_LABEL="ksql_cli.base - Conteco "
export CONTECO_DESCRIPTION="Confluent KSQL CLI base image, using default configuration."

export CONTECO_TYPE="ksql_cli"
export CONTECO_NAME="base"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.ksql_cli:5.4.0"
export CONTECO_BUILD="image-base"
