---
version: '3'
services:

# START SERVICE ksql_cli.base
  ksql_cli:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksql_cli.base:5.4.0
    environment: []
    command: []
    volumes: []
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_KSQL_CLI_COMPOSE_EXTENSIONS}
# END SERVICE ksql_cli.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
