---
version: '3'
services:

# START SERVICE ksql_cli.base
  ksql_cli:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksql_cli.base:5.4.0
    environment: []
    command: []
    volumes: []
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      replicas: ${CONTECO_DC_KSQL_CLI_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_KSQL_CLI_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${CONTECO_DC_KSQL_CLI_DEPLOY_LABELS}]
    labels: [${CONTECO_DC_KSQL_CLI_LABELS}]
# END SERVICE ksql_cli.base

volumes: {}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
